spring:
  application:
    name: "user"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    config:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    json:
      name: demo_json_queue
  exchange:
    name: demo_exchange
  routing:
    json:
      key: demo_json_routing


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


endpoints:
  shutdown:
    enabled: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG