spring:
  application:
    name: USER-SERVICE
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/fin_user
    username: root
    password: root
  cloud:
    config:
      enabled: false

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
